export interface climasmetropolitana{
    id:number;
    nombre:string;
    tipo:string;
    dia:string;
    imagen:string;
    temperatura:string;
}

export let Listaclimasmetropolitana:Array<climasmetropolitana>=[
    {
    id:1,
    nombre:"Valparaiso",
    tipo:"Soleado",
    dia:"Lunes",
    imagen:"soleado.png",
    temperatura:"18°C"
    },
    {
    id:2,
    nombre:"Valparaiso",
    tipo:"Lluvioso",
    dia:"Martes",
    imagen:"lluvioso.png",
    temperatura:"9°C"
    },
    {
        id:3,
        nombre:"Valparaiso",
        tipo:"Nublado",
        dia:"Miercoles",
        imagen:"nublado.png",
        temperatura:"11°C"
    },
    {
        id:4,
        nombre:"Valparaiso",
        tipo:"Tormenta",
        dia:"Jueves",
        imagen:"tormenta.png",
        temperatura:"7°C"
    },
    {
        id:5,
        nombre:"Valparaiso",
        tipo:"nublado",
        dia:"Viernes",
        imagen:"nublado.png",
        temperatura:"22°C"
    },
    {
        id:6,
        nombre:"Valparaiso",
        tipo:"soleado",
        dia:"Sábado",
        imagen:"soleado.png",
        temperatura:"10°C"
    },
    {
        id:7,
        nombre:"Valparaiso",
        tipo:"lluvioso",
        dia:"Domingo",
        imagen:"lluvioso.png",
        temperatura:"7°C"
    },
]
